[package]
name = "knownext-storage"
version = "2.0.1"
edition = "2021"
license = "Apache-2.0"

[dependencies]
base64 = "0.22"
knownext-ai = { path = "../knownext-ai" }
knownext-core = { path = "../knownext-core" }
knownext-docs = { path = "../knownext-docs" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
